MA-8557 [Android_IMX8] overwrite the default offset of ramdisk and dts
Overwrite the default offset of ramdisk and dts on imx8, the default offset
will cause overlap.

Can't boot up kernel with below log.
The size of kernel image is so large that it will cover dtb.
Change the offset of ramdisk and dts.

ERROR LOG:
kernel   @ 80008000 (15051264)
ramdisk  @ 81000000 (1448910)
fdt      @ 80f00000 (40148)
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
resetting ...
SCI reboot request

Change-Id: I60778dd0c554c925f5c50f635ccd944cd0a4706b
Signed-off-by: Richard Liu <xuegang.liu@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/1041
Reviewed-by: guoyin.chen <guoyin.chen@nxp.com>